allowBuilds:
  '@google/genai': false
  '@parcel/watcher': true
  '@prisma/engines': true
  '@sentry/cli': true
  '@swc/core': true
  core-js: true
  esbuild: true
  prisma: true
  protobufjs: false
  unrs-resolver: true
